name: addressfolio
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  http:
  jaguar: ^0.6.0
  jaguar_serializer:
  mongo_dart:
  jaguar_mongo: '>=0.5.0 <0.6.0'
  jaguar_auth:
  # jaguar_json:

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
